{% set name = "glue-samp" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glue-samp-{{ version }}.tar.gz
  sha256: 5d3d45451acab18dc64e241484f694056912245d8a4a0cda9251d594e45a9385

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - glue-core >=0.15
    - numpy
    - qtpy

test:
  imports:
    - glue_samp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/glue-viz/glue-samp
  summary: A SAMP plugin for glue
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
